LiDARの追加
rt-net/raspimouse_description pull request #38
Opened 2022-07-04 06:20 UTC by shu-rt

# What does this implement/fix?

LIDAR用のURDFを追加し、LDSとRPLIDARも表示可能にしました

# Does this close any currently open issues?

なし

# How has this been tested?

実際のロボットを計測し、位置の調整を行いました

# Any other comments?

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2022-07-06 00:25 UTC, ShotaAk commented
@shu-rt PRのマージ先を`ros2`ブランチに変更しました。

2022-07-06 00:57 UTC, ShotaAk commented
Humble環境でrplidar, ldsのオプションが機能することを確認しました。  
urgオプションも問題なく機能しています。

外観についてコメントを残します。

![image](https://user-images.githubusercontent.com/18494952/177439678-ddd17bc9-d519-49f0-8d3d-5e9448b983e8.png)

![image](https://user-images.githubusercontent.com/18494952/177440054-2abbf197-9827-437b-b48a-14a48f1cd2be.png)

2022-07-06 02:33 UTC, ShotaAk requested changes
動作確認完了しました。

レビューコメントの確認お願いします。

2022-07-06 02:33 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <material name="dark"/>
`dark`というマテリアルが存在しないため、モデルが赤色に表示されました。

下記のような定義をファイル上部に追加してください。
また、`dark`だと何色かわかりにくいため、`black`や`gray`等の名称に変更してください

実装例：https://github.com/rt-net/crane_plus/blob/498a1fe836a2aba3163c5bc07e0a5a65bde7bacb/crane_plus_description/urdf/crane_plus.xacro#L5-L7

```xml
  <material name="black">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
```

2022-07-06 02:33 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +      </visual>
`legs`は、rplidarとurgで同じ位置に柱を立てています。マクロにして共通化しましょう。
柱のlengthとradiusをマクロの引数にすれば対応できます。

他のファイルからは参照しないマクロなので、マクロはファイルの上部で作成してください。

2022-07-06 02:33 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <!-- </geometry> -->
不要なコメントは削除してください。

2022-07-06 02:33 UTC, ShotaAk commented on urdf/raspimouse.urdf.xacro
> +    </xacro:if>
コメントです。gazeboの項目については動作確認していません。

パラメータの数値のみ確認しています。

2022-07-06 02:33 UTC, ShotaAk commented on urdf/raspimouse.urdf.xacro
> +      <xacro:lidar_gazebo sensor_link_name="$(arg lidar_frame)" base_rad="0" rad_range="6.28" min_range="0.15" max_range="10" />
製品スペックに合わせて、12 mに変更したいです。
https://www.slamtec.com/en/Lidar/A1Spec

```suggestion
      <xacro:lidar_gazebo sensor_link_name="$(arg lidar_frame)" base_rad="0" rad_range="6.28" min_range="0.15" max_range="12" />
```

2022-07-06 02:33 UTC, ShotaAk commented on urdf/body/option.urdf.xacro
> +        <!-- </geometry> -->
不要なコメントは削除してください

```suggestion
```

2022-07-06 02:33 UTC, ShotaAk commented on urdf/body/option.urdf.xacro
> +          <box size="0.117 0.080 0.087" />
ライダーマウントの衝突モデルが大きすぎるので修正してください。boxで表現するのはokです。

衝突判定を設けるのはマウントの天板部分だけで良いと思います。

![image](https://user-images.githubusercontent.com/18494952/177449454-ad48962d-7afa-4cd6-95c9-6df24ca227ee.png)

2022-07-06 02:33 UTC, ShotaAk commented on urdf/body/option.urdf.xacro
> +        <origin xyz="0 0 0.07" />
重心位置が大きくずれているため修正お願いします

![image](https://user-images.githubusercontent.com/18494952/177449353-194ee863-6aef-4129-9d7f-4d6bdacdd577.png)

2022-07-06 02:33 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <xacro:cylinder_inertia m="0.16" r="0.025" h="0.07" />
LDS の Inertia のheightが高いので修正してください。
3 cm程度で良いと思います。

厳密に再現するのは難しいので、
支柱を無視して近似してokです。（lidarの回転部分だけ、円柱近似するイメージ）

![image](https://user-images.githubusercontent.com/18494952/177450276-68856d99-4d92-47d6-b727-06875e39ffb4.png)

2022-07-06 02:33 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <origin xyz="0 0 -0.01815" />
衝突モデルの大きさは良いですが、位置が下寄りになっているので上げてください。

支柱は無視して、LiDAR本体の上面下面が覆えるくらいの配置で良いです。

![image](https://user-images.githubusercontent.com/18494952/177450798-dfdca896-1032-4e27-b5e8-7596ae7afa86.png)

2022-07-06 02:33 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +      </collision>
rplidarの衝突モデルは形状が大きすぎます。 
支柱は無視して良いので、LDSと同じパラメータにしてください

![image](https://user-images.githubusercontent.com/18494952/177451221-3086bf02-f17b-4a7a-be79-893674307014.png)

2022-07-06 02:33 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <xacro:cylinder_inertia m="0.16" r="0.025" h="0.07" />
rplidarのイナーシャについて

LDSと同じく、厳密に再現するのは難しいので、
支柱を無視して近似してokです。（lidarの回転部分だけ、円柱近似するイメージ）

![image](https://user-images.githubusercontent.com/18494952/177451734-9d6b4b38-a087-4cd8-88a1-243902403f4e.png)

2022-07-06 02:33 UTC, ShotaAk commented on urdf/raspimouse.urdf.xacro
> +      <origin xyz="0.0 0.0 0.0345" rpy="0 0 3.14" />
jointの姿勢が、z軸周りに180度回転されているのでokです。

下記のコマンドでlaserトピックの表示を確認しています。

```sh
# ターミナル1
ros2 launch hls_lfcd_lds_driver hlds_laser.launch.py
# ターミナル2
rviz2
# ターミナル3
ros2 run tf2_ros static_transform_publisher --frame-id base_link --child-frame-id laser
```

2022-07-06 06:09 UTC, shu-rt commented on urdf/sensors/lidar.urdf.xacro
> +        <material name="dark"/>
僕の環境だと黒い物体で表示されてたのでちょっと不思議な感じありますです  
でも`dark`だとたしかに分かりづらいので`black`で定義しておきます。

2022-07-06 06:51 UTC, shu-rt commented on urdf/sensors/lidar.urdf.xacro
> +      </visual>
すっきりするので賛成です。  
足の高さが変わるためOriginのZ方向も調整する必要があります。なので、引数はlength, radius, z_posの3つになります

2022-07-06 08:47 UTC, shu-rt commented on urdf/body/option.urdf.xacro
> +          <box size="0.117 0.080 0.087" />
調整しました

2022-07-06 08:47 UTC, shu-rt commented on urdf/body/option.urdf.xacro
> +        <origin xyz="0 0 0.07" />
調整しました

2022-07-06 08:48 UTC, shu-rt commented on urdf/sensors/lidar.urdf.xacro
> +        <xacro:cylinder_inertia m="0.16" r="0.025" h="0.07" />
調整しました

2022-07-06 08:48 UTC, shu-13 commented on urdf/sensors/lidar.urdf.xacro
> +        <origin xyz="0 0 -0.01815" />
調整しました

2022-07-06 08:49 UTC, shu-rt commented on urdf/sensors/lidar.urdf.xacro
> +      </collision>
すみません、計測間違えてました。  
調整しました

2022-07-06 08:49 UTC, shu-rt commented on urdf/sensors/lidar.urdf.xacro
> +        <xacro:cylinder_inertia m="0.16" r="0.025" h="0.07" />
調整しました

2022-07-07 00:40 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <material name="dark"/>
変更を確認しました。okです

2022-07-07 00:43 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +      </visual>
変更を確認しました。okです。

2022-07-07 00:46 UTC, ShotaAk commented on urdf/body/option.urdf.xacro
> +          <box size="0.117 0.080 0.087" />
![image](https://user-images.githubusercontent.com/18494952/177666124-21fcc1d8-af1b-4ab2-97e8-aeecbe5bbce2.png)

変更を確認しました。okです。

2022-07-07 00:51 UTC, ShotaAk commented on urdf/body/option.urdf.xacro
> +        <origin xyz="0 0 0.07" />
若干ずれていました。

![image](https://user-images.githubusercontent.com/18494952/177666320-f9150d76-2509-4da0-9e90-a98382abe369.png)

https://github.com/rt-net/raspimouse_description/pull/38/commits/46d68b03683ed49359c9d92e3835011c0092cbdf
にて、衝突モデルに合わせて修正しました。↓

![image](https://user-images.githubusercontent.com/18494952/177666419-95ed3a77-0969-4f4d-85d3-857a9df7fa2d.png)

2022-07-07 00:53 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <origin xyz="0 0 -0.01815" />
![image](https://user-images.githubusercontent.com/18494952/177666699-91fd95e9-9e98-4904-8001-bbc83cc96512.png)

確認しました。okです

2022-07-07 00:54 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <xacro:cylinder_inertia m="0.16" r="0.025" h="0.07" />
![image](https://user-images.githubusercontent.com/18494952/177666767-fc9feb72-6c26-418e-baf7-7b12e7d178f9.png)

確認しました。いいですね。OKです。

2022-07-07 00:55 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +      </collision>
![image](https://user-images.githubusercontent.com/18494952/177666893-bf753f8a-4541-479f-b7d9-e28bbebb3794.png)

確認しました。okです

2022-07-07 00:56 UTC, ShotaAk commented on urdf/sensors/lidar.urdf.xacro
> +        <xacro:cylinder_inertia m="0.16" r="0.025" h="0.07" />
![image](https://user-images.githubusercontent.com/18494952/177666944-7b31685c-8c8c-40a3-a3b5-9302501ac2e3.png)

確認しました。okです。

2022-07-07 00:57 UTC, ShotaAk approved these changes
LGTM

2022-07-07 00:57 UTC, merged