robot_description_loaderを実装
rt-net/raspimouse_description pull request #42
Opened 2023-09-14 07:36 UTC by YusukeKato

# What does this implement/fix?

robot_description_loaderを実装しました。

# Does this close any currently open issues?

しません。

# How has this been tested?

pytestを実行してテストが通ることを確認しました。

# Any other comments?

`colcon test`が通るように空行を削除した箇所があります。

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-09-15 02:50 UTC, ShotaAk commented
display.launch.pyでdescription_loaderを使うように変更お願いします

2023-09-15 02:50 UTC, ShotaAk commented
github上でテストを実行したいのでCIファイルを追加してください

2023-09-20 08:10 UTC, Tiryoh requested changes

2023-09-20 08:10 UTC, Tiryoh commented on package.xml
>    <maintainer email="shop@rt-net.jp">RT Corporation</maintainer>
```suggestion
  <maintainer email="support@rt-net.jp">RT Corporation</maintainer>
```

連絡先変わっているので合わせておくのが良いと思います。

2023-09-20 08:10 UTC, Tiryoh commented on package.xml
>    <license>MIT</license>
```suggestion

  <license>MIT</license>
  
  <author email="daisuke.sato@rt-net.jp">Daisuke Sato</author>
  <author email="s.aoki@rt-net.jp">Shota Aoki</author>
  <author email="yusuke.kato@rt-net.jp">Yusuke Kato</author>
```

maintainer, license, authorの順にする必要があります。authorはそのまま残したほうが良いと思います。

2023-09-20 10:19 UTC, ShotaAk requested changes
レビューコメント反映し忘れていました。。。コメントの確認お願いします。

2023-09-20 10:19 UTC, ShotaAk commented on urdf/raspimouse.urdf.xacro
> +  <xacro:arg name="gz_control_config_file_path" default="" />
今回の変更でこれらの引数は使用されていません。
機能追加時に引数を追加してください。
```suggestion
```

2023-09-20 10:19 UTC, ShotaAk commented on raspimouse_description/robot_description_loader.py
> +        self.gz_control_config_file_path = ''
これらの引数は今回の変更で使用されていないので削除お願いします。

2023-09-20 10:19 UTC, ShotaAk commented on raspimouse_description/robot_description_loader.py
> +        self.use_gazebo = 'false'
display.launch.pyでも使用されている引数、`lidar`と`lidar_frame`に対応してください。

2023-09-20 10:19 UTC, ShotaAk commented on test/test_robot_description_loader.py
引数、lidarとlidar_frameのテストを追加してください。

引数lidarについては、"none", "urg", "lds", or "rplidar"　が正しく反映されることを検証してください

2023-09-22 01:19 UTC, ShotaAk approved these changes
diplay.launch.pyが動作すること確認できました。
テストも実行できており、良いと思います。

2023-09-22 01:36 UTC, merged